<?

/**
 * The FeaturePhp\File\ExtendFile class.
 */

namespace FeaturePhp\File;
use \FeaturePhp as fphp;

/**
 * A file that can be extended by different artifacts.
 * An extended file is a {@see File} generated by a {@see \FeaturePhp\Generator\ExtendGenerator}.
 * For concrete implementations, see {@see ChunkFile} or {@see TemplateFile}.
 */
interface ExtendFile {
    /**
     * Extends the file.
     * This is expected to be called only be a {@see \FeaturePhp\Generator\ExtendGenerator}.
     * @param \FeaturePhp\Specification\Specification $specification
     */
    public function extend($specification);
}

?>