<?

/**
 * The FeaturePhp\File\RefinedFile class.
 */

namespace FeaturePhp\File;
use \FeaturePhp as fphp;

/**
 * A text file generated from a set of roles.
 * A refined file is a {@see TextFile} generated by a {@see \FeaturePhp\Generator\CollaborationGenerator}.
 * It is composed from several roles inside multiple collaborations, see {@see \FeaturePhp\Collaboration\Role}
 * and {@see \FeaturePhp\Collaboration\Collaboration}.
 */
class RefinedFile extends TextFile {
    /**
     * @var \FeaturePhp\Collaboration\Role[] $roles all roles needed to refine this file
     */
    private $roles;
    
    /**
     * Creates a refined file.
     * @param string $fileTarget
     * @param \FeaturePhp\Collaboration\Role[] $roles
     */
    public function __construct($fileTarget, $roles) {
        parent::__construct($fileTarget);
        $this->roles = $roles;
    }

    /**
     * Returns the refined file's content.
     * It is generated using an appropriate composition mechanism (see {@see \FeaturePhp\Collaboration\Composition}).
     * @return FileContent
     */
    public function getContent() {
        $composition = fphp\Collaboration\Composition::fromKind($this->roles[0]->getKind());
        foreach ($this->roles as $role)
            $composition = $composition->refine($role);
        return $composition->getContent();
    }
}

?>